### ISSUE TITLE
validate_uniqueness_of

### ISSUE THREAD

**Issue by kronn** [joshwlewis/validates_by_schema#3]
I saw that (at least in version 0.3.0) unique indexes are not translated into validations. Would that be a feature that would fit this gem?

**Comment by codez** [comment]
I think this should actually be doable with the `indexes` method on the connection. Would you like to work on that?

**Comment by kronn** [comment]
Yes, I just wanted to clarify if this is in scope or not. It sounds straightforward, yet interesting. I'll prep a PR, hopefully in the coming days.
